server:
  port: 8080

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

app:
  mail:
    enabled: ${APP_MAIL_ENABLED}
    from-address: ${APP_MAIL_FROM}
  weather:
    provider: ${APP_WEATHER_PROVIDER}
    geocoding-base-url: ${APP_WEATHER_GEOCODING_BASE_URL}
    forecast-base-url: ${APP_WEATHER_FORECAST_BASE_URL}
    geocoding-language: ${APP_WEATHER_GEOCODING_LANGUAGE}
    geocoding-country-code: ${APP_WEATHER_GEOCODING_COUNTRY_CODE}
