server:
  port: 8080

spring:
  config:
    import: file:.env[.properties]
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 0
        max.block.ms: 3000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.weatherkafka.*
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

app:
  mail:
    enabled: ${APP_MAIL_ENABLED}
    from-address: ${APP_MAIL_FROM}
  weather:
    provider: ${APP_WEATHER_PROVIDER}
    geocoding-base-url: ${APP_WEATHER_GEOCODING_BASE_URL}
    forecast-base-url: ${APP_WEATHER_FORECAST_BASE_URL}
    geocoding-language: ${APP_WEATHER_GEOCODING_LANGUAGE}
    geocoding-country-code: ${APP_WEATHER_GEOCODING_COUNTRY_CODE}
